using CardioSimulator.Core.Domain;

namespace CardioSimulator.App.Localization;

/// <summary>
/// Language-aware UI strings, ported from the Android <c>res/values*/strings.xml</c>.
/// <see cref="Current"/> selects the active language; <see cref="Changed"/> fires when it
/// switches so the UI can re-pull localized text. Unknown keys fall back to English.
/// </summary>
public static class AppStrings
{
    private static Language _current = Language.EN;

    /// <summary>Raised when <see cref="Current"/> changes (UI rebuilds on this).</summary>
    public static event Action? Changed;

    public static Language Current
    {
        get => _current;
        set
        {
            if (_current == value) return;
            _current = value;
            Changed?.Invoke();
        }
    }

    private static string S(string key)
    {
        var table = _current switch
        {
            Language.RU => Ru,
            Language.ZH => Zh,
            Language.ES => Es,
            _ => En,
        };
        if (table.TryGetValue(key, out var value)) return value;
        return En.TryGetValue(key, out var en) ? en : key;
    }

    // Data source
    public static string DataSourceTitle => S("data_source_title");
    public static string DataSourceDescription => S("data_source_description");
    public static string DataSourcePickFolder => S("data_source_pick_folder");
    public static string DataSourceChangeFolder => S("data_source_change_folder");
    public static string DataSourceLoading => S("data_source_loading");
    public static string DataSourceContinue => S("data_source_continue");
    public static string DataSourceRetry => S("data_source_retry");
    public static string DataSourceShowDetails => S("data_source_show_details");
    public static string DataSourceClose => S("data_source_close");
    public static string DataSourceErrorBadManifest => S("data_source_error_bad_manifest");
    public static string DataSourceErrorUnreadable => S("data_source_error_unreadable");
    public static string DataSourceErrorEmpty => S("data_source_error_empty");
    public static string DataSourceExportZip => S("data_source_export_zip");
    public static string RhythmSearchPlaceholder => S("rhythm_search_placeholder");

    public static string DataSourceLoadedFormat(int count) => string.Format(S("data_source_loaded_format"), count);
    public static string DataSourcePathologiesTitle(int count) => string.Format(S("data_source_pathologies_title"), count);

    // Settings
    public static string SettingsTitle => S("settings_title");
    public static string SettingsBlankSheet => S("settings_blank_sheet");
    public static string ModeCourseConstructor => S("mode_course_constructor");
    public static string CompareButton => S("compare_button");
    public static string CalcDerivedLeads => S("calc_derived_leads");
    public static string CompareSelectPathologies => S("compare_select_pathologies");
    public static string ComparePresets => S("compare_presets");
    public static string CompareSavePresetLabel => S("compare_save_preset_label");
    public static string CompareSavePresetPlaceholder => S("compare_save_preset_placeholder");
    public static string CompareModeTitle => S("compare_mode_title");
    public static string ComparePlaceholder => S("compare_placeholder");
    public static string CompareLeadLabel => S("compare_lead_label");
    public static string CompareExit => S("compare_exit");
    public static string CompareStartNew => S("compare_start_new");
    public static string CompareApplyPreset => S("compare_apply_preset");
    public static string CompareTargetTitle => S("compare_target_title");
    public static string CommonOk => S("common_ok");
    public static string CommonCancel => S("common_cancel");
    public static string CommonSave => S("common_save");
    public static string SettingsClose => S("settings_close");
    public static string SettingsColorScheme => S("settings_color_scheme");
    public static string ThemeLight => S("theme_light");
    public static string ThemeDark => S("theme_dark");
    public static string SettingsGridScheme => S("settings_grid_scheme");
    public static string SettingsLanguage => S("settings_language");
    public static string SettingsTcpTitle => S("settings_tcp_title");
    public static string SettingsTcpIp => S("settings_tcp_ip");
    public static string SettingsTcpPort => S("settings_tcp_port");
    public static string TcpConnect => S("tcp_connect");
    public static string TcpDisconnect => S("tcp_disconnect");
    public static string TcpStatusConnected => S("tcp_status_connected");
    public static string TcpStatusConnecting => S("tcp_status_waiting");
    public static string TcpStatusDisconnected => S("tcp_status_disconnected");
    public static string TcpStatusError => S("tcp_status_error");
    public static string SettingsTcpIpError => S("settings_tcp_ip_error");
    public static string SettingsTcpPortError => S("settings_tcp_port_error");

    // Significant points / ECG annotations
    public static string EcgIntervalP => S("ecg_interval_p");
    public static string EcgIntervalQrs => S("ecg_interval_qrs");
    public static string EcgIntervalT => S("ecg_interval_t");
    public static string EcgIntervalPr => S("ecg_interval_pr");
    public static string EcgIntervalSt => S("ecg_interval_st");
    public static string EcgIntervalQt => S("ecg_interval_qt");
    public static string EcgIntervalRr => S("ecg_interval_rr");
    public static string EcgRrValueFormat(double seconds) => string.Format(S("ecg_rr_value_format"), seconds);
    public static string EditorSignificantPoints => S("editor_significant_points");
    public static string EditorPWave => S("editor_p_wave");
    public static string EditorQrsComplex => S("editor_qrs_complex");
    public static string EditorTWave => S("editor_t_wave");
    public static string EditorSelectPointHint => S("editor_select_point_hint");
    public static string EditorRhythmsTitle => S("editor_rhythms_title");
    public static string EditorSampleLabel(int index) => string.Format(S("editor_sample_label"), index);
    public static string EditorSetTimeTitle => S("editor_set_time_title");
    public static string EditorTimeUnit => S("editor_time_unit");
    public static string EditorTimeFormat(int ms) => string.Format(S("editor_time_format"), ms);
    public static string EditorSetAdcTitle => S("editor_set_adc_title");
    public static string EditorAdcLabel => S("editor_adc_label");
    public static string EditorAdcFormat(string value) => string.Format(S("editor_adc_format"), value);
    public static string MonitorSpeedTitle => S("monitor_speed_title");
    public static string MonitorSpeedUnit => S("monitor_speed_unit");
    public static string MonitorSpeedFormat(int speed) => string.Format(S("monitor_speed_format"), speed);
    public static string MonitorCountFormat(int count) => string.Format(S("monitor_count_format"), count);
    public static string MonitorColumnsOne => S("monitor_columns_one");
    public static string MonitorColumnsTwo => S("monitor_columns_two");
    public static string MonitorColumnsGrid => S("monitor_columns_grid");
    public static string MonitorColumnsOneShort => S("monitor_columns_one_short");
    public static string MonitorColumnsTwoShort => S("monitor_columns_two_short");
    public static string MonitorColumnsGridShort => S("monitor_columns_grid_short");
    public static string MonitorElectrodes => S("monitor_electrodes");
    public static string MonitorEmdEbpa => S("monitor_emd_ebpa");
    public static string MonitorMuscle => S("monitor_muscle");
    public static string MonitorEos => S("monitor_eos");
    public static string MonitorHrFormat(int hr) => string.Format(S("monitor_hr_format"), hr);
    public static string MonitorTips => S("monitor_tips");

    public static string EcgPointLabel(EcgPointType type) => S(type switch
    {
        EcgPointType.P_START => "ecg_point_p_start",
        EcgPointType.P_PEAK => "ecg_point_p_peak",
        EcgPointType.P_END => "ecg_point_p_end",
        EcgPointType.Q_PEAK => "ecg_point_q_peak",
        EcgPointType.R_PEAK => "ecg_point_r_peak",
        EcgPointType.S_PEAK => "ecg_point_s_peak",
        EcgPointType.QRS_START => "ecg_point_qrs_start",
        EcgPointType.QRS_END => "ecg_point_qrs_end",
        EcgPointType.T_START => "ecg_point_t_start",
        EcgPointType.T_PEAK => "ecg_point_t_peak",
        EcgPointType.T_END => "ecg_point_t_end",
        _ => "ecg_point_p_peak",
    });

    public static string ModeName(OperatingMode mode) => S(mode.TitleResourceKey());
    public static string GridSchemeLabel(GridScheme scheme) => S(scheme.LabelResourceKey());

    private static readonly Dictionary<string, string> En = new()
    {
        ["data_source_title"] = "ECG Data",
        ["data_source_description"] = "Select a ZIP archive on your device containing the ECG data.",
        ["data_source_pick_folder"] = "Select ZIP archive",
        ["data_source_change_folder"] = "Change ZIP archive",
        ["data_source_loading"] = "Loading data…",
        ["data_source_continue"] = "Continue",
        ["data_source_retry"] = "Pick another ZIP",
        ["data_source_show_details"] = "Show Details",
        ["data_source_close"] = "Close",
        ["data_source_error_bad_manifest"] = "The ZIP archive contains an invalid or missing manifest file.",
        ["data_source_error_unreadable"] = "The selected ZIP archive is no longer accessible.",
        ["data_source_error_empty"] = "No ECG files were found in the selected ZIP archive.",
        ["data_source_export_zip"] = "Export ZIP",
        ["data_source_loaded_format"] = "Loaded {0} pathologies",
        ["data_source_pathologies_title"] = "Loaded Pathologies ({0})",
        ["rhythm_search_placeholder"] = "Rhythm…",
        ["mode_course_constructor"] = "Course Constructor",
        ["compare_button"] = "Compare",
        ["settings_blank_sheet"] = "Blank Sheet",
        ["calc_derived_leads"] = "Calc Derived Leads",
        ["compare_select_pathologies"] = "Select pathologies to overlay:",
        ["compare_presets"] = "Saved presets",
        ["compare_save_preset_label"] = "Save layout as preset:",
        ["compare_save_preset_placeholder"] = "Preset name…",
        ["compare_mode_title"] = "Compare mode",
        ["compare_placeholder"] = "Tap to add comparison",
        ["compare_lead_label"] = "Lead",
        ["compare_exit"] = "Exit comparison",
        ["compare_start_new"] = "New comparison",
        ["compare_apply_preset"] = "Apply preset",
        ["compare_target_title"] = "Select comparison",
        ["common_ok"] = "OK",
        ["common_cancel"] = "Cancel",
        ["common_save"] = "Save",
        ["settings_title"] = "Settings",
        ["settings_close"] = "CLOSE",
        ["settings_color_scheme"] = "App Theme",
        ["theme_light"] = "Light",
        ["theme_dark"] = "Dark",
        ["settings_grid_scheme"] = "Monitor Grid Scheme",
        ["settings_language"] = "Language",
        ["settings_tcp_title"] = "TCP Connection",
        ["settings_tcp_ip"] = "IP Address",
        ["settings_tcp_port"] = "Port",
        ["tcp_connect"] = "Connect",
        ["tcp_disconnect"] = "Disconnect",
        ["tcp_status_connected"] = "Connected",
        ["tcp_status_waiting"] = "Waiting…",
        ["tcp_status_disconnected"] = "Disconnected",
        ["tcp_status_error"] = "Error",
        ["mode_teaching"] = "Teaching",
        ["mode_testing"] = "Testing",
        ["mode_examination"] = "Examination",
        ["mode_oske"] = "OSKE",
        ["mode_editor"] = "Editor",
        ["grid_scheme_pink"] = "Pink",
        ["grid_scheme_blue_gray"] = "Blue/Gray",
        ["editor_significant_points"] = "Significant Points",
        ["editor_sample_label"] = "Sample: {0}",
        ["editor_p_wave"] = "P Wave",
        ["editor_qrs_complex"] = "QRS Complex",
        ["editor_t_wave"] = "T Wave",
        ["editor_select_point_hint"] = "Select a point on the chart to mark it",
        ["editor_rhythms_title"] = "Rhythms",
        ["editor_set_time_title"] = "Set Time (ms)",
        ["editor_time_unit"] = "ms",
        ["editor_time_format"] = "{0} ms",
        ["editor_set_adc_title"] = "Set ADC Value",
        ["editor_adc_label"] = "ADC",
        ["editor_adc_format"] = "ADC: {0}",
        ["monitor_speed_title"] = "Speed",
        ["monitor_speed_unit"] = "mm/s",
        ["monitor_speed_format"] = "{0} mm/s",
        ["monitor_count_format"] = "{0}×",
        ["monitor_columns_one"] = "1 Column",
        ["monitor_columns_two"] = "2 Columns",
        ["monitor_columns_grid"] = "Grid",
        ["monitor_columns_one_short"] = "1 Col",
        ["monitor_columns_two_short"] = "2 Cols",
        ["monitor_columns_grid_short"] = "Grid",
        ["monitor_electrodes"] = "Electrodes",
        ["monitor_emd_ebpa"] = "EMD/EBPA",
        ["monitor_muscle"] = "Muscle",
        ["monitor_eos"] = "EOS",
        ["monitor_hr_format"] = "HR {0}",
        ["monitor_tips"] = "Tips",
        ["settings_tcp_ip_error"] = "Invalid IP Address format",
        ["settings_tcp_port_error"] = "Port must be 0–65535",
        ["ecg_point_p_start"] = "P Start",
        ["ecg_point_p_peak"] = "P Peak",
        ["ecg_point_p_end"] = "P End",
        ["ecg_point_q_peak"] = "Q Peak",
        ["ecg_point_r_peak"] = "R Peak",
        ["ecg_point_s_peak"] = "S Peak",
        ["ecg_point_qrs_start"] = "QRS Start",
        ["ecg_point_qrs_end"] = "QRS End",
        ["ecg_point_t_start"] = "T Start",
        ["ecg_point_t_peak"] = "T Peak",
        ["ecg_point_t_end"] = "T End",
        ["ecg_interval_p"] = "P",
        ["ecg_interval_qrs"] = "QRS",
        ["ecg_interval_t"] = "T",
        ["ecg_interval_pr"] = "PR",
        ["ecg_interval_st"] = "ST",
        ["ecg_interval_qt"] = "QT",
        ["ecg_interval_rr"] = "R-R",
        ["ecg_rr_value_format"] = "R-R: {0:0.000} s",
    };

    private static readonly Dictionary<string, string> Ru = new()
    {
        ["data_source_title"] = "Данные ЭКГ",
        ["data_source_description"] = "Выберите на устройстве ZIP-архив, содержащий данные ЭКГ.",
        ["data_source_pick_folder"] = "Выбрать ZIP-архив",
        ["data_source_change_folder"] = "Сменить ZIP-архив",
        ["data_source_loading"] = "Загрузка данных…",
        ["data_source_continue"] = "Продолжить",
        ["data_source_retry"] = "Выбрать другой архив",
        ["data_source_show_details"] = "Подробнее",
        ["data_source_close"] = "Закрыть",
        ["data_source_error_bad_manifest"] = "ZIP-архив содержит неверный или отсутствующий файл манифеста.",
        ["data_source_error_unreadable"] = "Выбранный архив больше недоступен.",
        ["data_source_error_empty"] = "В выбранном архиве не найдены файлы ЭКГ.",
        ["data_source_export_zip"] = "Экспорт ZIP",
        ["data_source_loaded_format"] = "Загружено патологий: {0}",
        ["data_source_pathologies_title"] = "Загруженные патологии ({0})",
        ["rhythm_search_placeholder"] = "Ритм…",
        ["mode_course_constructor"] = "Конструктор курсов",
        ["compare_button"] = "Сравнение",
        ["settings_blank_sheet"] = "Чистый лист",
        ["calc_derived_leads"] = "Рассчитать отведения",
        ["compare_select_pathologies"] = "Выберите патологии для наложения:",
        ["compare_presets"] = "Сохранённые пресеты",
        ["compare_save_preset_label"] = "Сохранить раскладку как пресет:",
        ["compare_save_preset_placeholder"] = "Название пресета…",
        ["compare_mode_title"] = "Режим сравнения",
        ["compare_placeholder"] = "Нажмите, чтобы добавить",
        ["compare_lead_label"] = "Отведение",
        ["compare_exit"] = "Выйти из сравнения",
        ["compare_start_new"] = "Новое сравнение",
        ["compare_apply_preset"] = "Применить пресет",
        ["compare_target_title"] = "Выбор сравнения",
        ["common_ok"] = "ОК",
        ["common_cancel"] = "Отмена",
        ["common_save"] = "Сохранить",
        ["settings_title"] = "Настройки",
        ["settings_close"] = "ЗАКРЫТЬ",
        ["settings_color_scheme"] = "Тема приложения",
        ["theme_light"] = "Светлая",
        ["theme_dark"] = "Темная",
        ["settings_grid_scheme"] = "Сетка монитора",
        ["settings_language"] = "Язык",
        ["settings_tcp_title"] = "TCP соединение",
        ["settings_tcp_ip"] = "IP-адрес",
        ["settings_tcp_port"] = "Порт",
        ["tcp_connect"] = "Подключить",
        ["tcp_disconnect"] = "Отключить",
        ["tcp_status_connected"] = "Подключено",
        ["tcp_status_waiting"] = "Ожидание…",
        ["tcp_status_disconnected"] = "Отключено",
        ["tcp_status_error"] = "Ошибка",
        ["mode_teaching"] = "Обучение",
        ["mode_testing"] = "Тестирование",
        ["mode_examination"] = "Экзамен",
        ["mode_oske"] = "ОСКЭ",
        ["mode_editor"] = "Редактор",
        ["grid_scheme_pink"] = "Розовая",
        ["grid_scheme_blue_gray"] = "Сине-серая",
        ["editor_significant_points"] = "Значимые точки",
        ["editor_sample_label"] = "Точка: {0}",
        ["editor_p_wave"] = "Зубец P",
        ["editor_qrs_complex"] = "Комплекс QRS",
        ["editor_t_wave"] = "Зубец T",
        ["editor_select_point_hint"] = "Выберите точку на графике, чтобы отметить ее",
        ["editor_rhythms_title"] = "Ритмы",
        ["editor_set_time_title"] = "Установить время (мс)",
        ["editor_time_unit"] = "мс",
        ["editor_time_format"] = "{0} мс",
        ["editor_set_adc_title"] = "Установить значение АЦП",
        ["editor_adc_label"] = "АЦП",
        ["editor_adc_format"] = "АЦП: {0}",
        ["monitor_speed_title"] = "Скорость",
        ["monitor_speed_unit"] = "мм/с",
        ["monitor_speed_format"] = "{0} мм/с",
        ["monitor_count_format"] = "{0}×",
        ["monitor_columns_one"] = "1 столбец",
        ["monitor_columns_two"] = "2 столбца",
        ["monitor_columns_grid"] = "Сетка",
        ["monitor_columns_one_short"] = "1 ст.",
        ["monitor_columns_two_short"] = "2 ст.",
        ["monitor_columns_grid_short"] = "Сетка",
        ["monitor_electrodes"] = "Электроды",
        ["monitor_emd_ebpa"] = "ЭМД/ЭБПА",
        ["monitor_muscle"] = "Мышцы",
        ["monitor_eos"] = "ЭОС",
        ["monitor_hr_format"] = "ЧСС {0}",
        ["monitor_tips"] = "Подсказки",
        ["settings_tcp_ip_error"] = "Неверный формат IP-адреса",
        ["settings_tcp_port_error"] = "Порт должен быть в диапазоне 0–65535",
        ["ecg_point_p_start"] = "P начало",
        ["ecg_point_p_peak"] = "P пик",
        ["ecg_point_p_end"] = "P конец",
        ["ecg_point_q_peak"] = "Q пик",
        ["ecg_point_r_peak"] = "R пик",
        ["ecg_point_s_peak"] = "S пик",
        ["ecg_point_qrs_start"] = "QRS начало",
        ["ecg_point_qrs_end"] = "QRS конец",
        ["ecg_point_t_start"] = "T начало",
        ["ecg_point_t_peak"] = "T пик",
        ["ecg_point_t_end"] = "T конец",
        ["ecg_interval_p"] = "P",
        ["ecg_interval_qrs"] = "QRS",
        ["ecg_interval_t"] = "T",
        ["ecg_interval_pr"] = "PR",
        ["ecg_interval_st"] = "ST",
        ["ecg_interval_qt"] = "QT",
        ["ecg_interval_rr"] = "R-R",
        ["ecg_rr_value_format"] = "R-R: {0:0.000} с",
    };

    private static readonly Dictionary<string, string> Zh = new()
    {
        ["data_source_title"] = "心电图数据",
        ["data_source_description"] = "请选择设备上包含心电图数据的 ZIP 压缩包。",
        ["data_source_pick_folder"] = "选择 ZIP 压缩包",
        ["data_source_change_folder"] = "更改 ZIP 压缩包",
        ["data_source_loading"] = "正在加载数据…",
        ["data_source_continue"] = "继续",
        ["data_source_retry"] = "选择其他 ZIP",
        ["data_source_show_details"] = "显示详情",
        ["data_source_close"] = "关闭",
        ["data_source_error_bad_manifest"] = "ZIP 压缩包包含无效或缺失的清单文件。",
        ["data_source_error_unreadable"] = "所选 ZIP 压缩包已无法访问。",
        ["data_source_error_empty"] = "所选 ZIP 压缩包中未找到心电图文件。",
        ["data_source_export_zip"] = "导出 ZIP",
        ["data_source_loaded_format"] = "已加载 {0} 个病理",
        ["data_source_pathologies_title"] = "已加载病理 ({0})",
        ["rhythm_search_placeholder"] = "心律…",
        ["settings_title"] = "设置",
        ["settings_close"] = "关闭",
        ["settings_color_scheme"] = "应用主题",
        ["theme_light"] = "浅色",
        ["theme_dark"] = "深色",
        ["settings_grid_scheme"] = "监视器网格方案",
        ["settings_language"] = "语言",
        ["settings_tcp_title"] = "TCP 连接",
        ["settings_tcp_ip"] = "IP 地址",
        ["settings_tcp_port"] = "端口",
        ["tcp_connect"] = "连接",
        ["tcp_disconnect"] = "断开连接",
        ["tcp_status_connected"] = "已连接",
        ["tcp_status_waiting"] = "等待中…",
        ["tcp_status_disconnected"] = "未连接",
        ["tcp_status_error"] = "错误",
        ["mode_teaching"] = "教学",
        ["mode_testing"] = "测试",
        ["mode_examination"] = "考试",
        ["mode_oske"] = "客观结构化临床考试",
        ["mode_editor"] = "编辑器",
        ["mode_course_constructor"] = "课程构建器",
        ["compare_button"] = "比较",
        ["compare_mode_title"] = "比较模式",
        ["compare_placeholder"] = "点击添加比较",
        ["compare_lead_label"] = "导联",
        ["compare_exit"] = "退出比较",
        ["compare_start_new"] = "新建比较",
        ["compare_apply_preset"] = "应用预设",
        ["compare_target_title"] = "选择比较",
        ["compare_presets"] = "已保存的预设",
        ["compare_save_preset_label"] = "将布局另存为预设：",
        ["compare_save_preset_placeholder"] = "预设名称…",
        ["common_ok"] = "确定",
        ["common_cancel"] = "取消",
        ["common_save"] = "保存",
        ["settings_blank_sheet"] = "空白页",
        ["calc_derived_leads"] = "计算衍生导联",
        ["grid_scheme_pink"] = "粉色",
        ["grid_scheme_blue_gray"] = "蓝灰色",
        ["editor_significant_points"] = "重要点",
        ["editor_sample_label"] = "样本: {0}",
        ["editor_p_wave"] = "P 波",
        ["editor_qrs_complex"] = "QRS 波群",
        ["editor_t_wave"] = "T 波",
        ["editor_select_point_hint"] = "在图表上选择一个点进行标记",
        ["editor_rhythms_title"] = "心律",
        ["editor_set_time_title"] = "设置时间 (ms)",
        ["editor_time_unit"] = "ms",
        ["editor_time_format"] = "{0} ms",
        ["editor_set_adc_title"] = "设置 ADC 值",
        ["editor_adc_label"] = "ADC",
        ["editor_adc_format"] = "ADC: {0}",
        ["monitor_speed_title"] = "速度",
        ["monitor_speed_unit"] = "毫米/秒",
        ["monitor_speed_format"] = "{0} 毫米/秒",
        ["monitor_count_format"] = "{0}×",
        ["monitor_columns_one"] = "1 列",
        ["monitor_columns_two"] = "2 列",
        ["monitor_columns_grid"] = "网格",
        ["monitor_columns_one_short"] = "1 列",
        ["monitor_columns_two_short"] = "2 列",
        ["monitor_columns_grid_short"] = "网格",
        ["monitor_electrodes"] = "电极",
        ["monitor_emd_ebpa"] = "无脉电活动",
        ["monitor_muscle"] = "肌肉",
        ["monitor_eos"] = "心电轴",
        ["monitor_hr_format"] = "心率 {0}",
        ["monitor_tips"] = "提示",
        ["settings_tcp_ip_error"] = "IP 地址格式无效",
        ["settings_tcp_port_error"] = "端口必须在 0–65535 之间",
        ["ecg_point_p_start"] = "P 开始",
        ["ecg_point_p_peak"] = "P 峰值",
        ["ecg_point_p_end"] = "P 结束",
        ["ecg_point_q_peak"] = "Q 峰值",
        ["ecg_point_r_peak"] = "R 峰值",
        ["ecg_point_s_peak"] = "S 峰值",
        ["ecg_point_qrs_start"] = "QRS 开始",
        ["ecg_point_qrs_end"] = "QRS 结束",
        ["ecg_point_t_start"] = "T 开始",
        ["ecg_point_t_peak"] = "T 峰值",
        ["ecg_point_t_end"] = "T 结束",
        ["ecg_interval_p"] = "P",
        ["ecg_interval_qrs"] = "QRS",
        ["ecg_interval_t"] = "T",
        ["ecg_interval_pr"] = "PR",
        ["ecg_interval_st"] = "ST",
        ["ecg_interval_qt"] = "QT",
        ["ecg_interval_rr"] = "R-R",
        ["ecg_rr_value_format"] = "R-R: {0:0.000} 秒",
    };

    private static readonly Dictionary<string, string> Es = new()
    {
        ["data_source_title"] = "Datos ECG",
        ["data_source_description"] = "Selecciona en tu dispositivo un archivo ZIP que contenga los datos ECG.",
        ["data_source_pick_folder"] = "Seleccionar archivo ZIP",
        ["data_source_change_folder"] = "Cambiar archivo ZIP",
        ["data_source_loading"] = "Cargando datos…",
        ["data_source_continue"] = "Continuar",
        ["data_source_retry"] = "Elegir otro ZIP",
        ["data_source_show_details"] = "Ver Detalles",
        ["data_source_close"] = "Cerrar",
        ["data_source_error_bad_manifest"] = "El archivo ZIP contiene un archivo de manifiesto no válido o ausente.",
        ["data_source_error_unreadable"] = "El archivo ZIP seleccionado ya no está accesible.",
        ["data_source_error_empty"] = "No se encontraron archivos ECG en el archivo ZIP seleccionado.",
        ["data_source_export_zip"] = "Exportar ZIP",
        ["data_source_loaded_format"] = "Patologías cargadas: {0}",
        ["data_source_pathologies_title"] = "Patologías Cargadas ({0})",
        ["rhythm_search_placeholder"] = "Ritmo…",
        ["settings_title"] = "Ajustes",
        ["settings_close"] = "CERRAR",
        ["settings_color_scheme"] = "Tema de la aplicación",
        ["theme_light"] = "Claro",
        ["theme_dark"] = "Oscuro",
        ["settings_grid_scheme"] = "Esquema de cuadrícula",
        ["settings_language"] = "Idioma",
        ["settings_tcp_title"] = "Conexión TCP",
        ["settings_tcp_ip"] = "Dirección IP",
        ["settings_tcp_port"] = "Puerto",
        ["tcp_connect"] = "Conectar",
        ["tcp_disconnect"] = "Desconectar",
        ["tcp_status_connected"] = "Conectado",
        ["tcp_status_waiting"] = "Esperando…",
        ["tcp_status_disconnected"] = "Desconectado",
        ["tcp_status_error"] = "Error",
        ["mode_teaching"] = "Enseñanza",
        ["mode_testing"] = "Prueba",
        ["mode_examination"] = "Examen",
        ["mode_oske"] = "ECOE",
        ["mode_editor"] = "Editor",
        ["mode_course_constructor"] = "Constructor de Cursos",
        ["compare_button"] = "Comparar",
        ["compare_mode_title"] = "Modo comparación",
        ["compare_placeholder"] = "Toca para añadir comparación",
        ["compare_lead_label"] = "Derivación",
        ["compare_exit"] = "Salir de comparación",
        ["compare_start_new"] = "Nueva comparación",
        ["compare_apply_preset"] = "Aplicar preajuste",
        ["compare_target_title"] = "Seleccionar comparación",
        ["compare_presets"] = "Preajustes guardados",
        ["compare_save_preset_label"] = "Guardar diseño como preajuste:",
        ["compare_save_preset_placeholder"] = "Nombre del preajuste…",
        ["common_ok"] = "Aceptar",
        ["common_cancel"] = "Cancelar",
        ["common_save"] = "Guardar",
        ["settings_blank_sheet"] = "Hoja en blanco",
        ["calc_derived_leads"] = "Calcular derivaciones",
        ["grid_scheme_pink"] = "Rosa",
        ["grid_scheme_blue_gray"] = "Azul/Gris",
        ["editor_significant_points"] = "Puntos significativos",
        ["editor_sample_label"] = "Muestra: {0}",
        ["editor_p_wave"] = "Onda P",
        ["editor_qrs_complex"] = "Complejo QRS",
        ["editor_t_wave"] = "Onda T",
        ["editor_select_point_hint"] = "Seleccione un punto en el gráfico para marcarlo",
        ["editor_rhythms_title"] = "Ritmos",
        ["editor_set_time_title"] = "Establecer tiempo (ms)",
        ["editor_time_unit"] = "ms",
        ["editor_time_format"] = "{0} ms",
        ["editor_set_adc_title"] = "Establecer valor ADC",
        ["editor_adc_label"] = "ADC",
        ["editor_adc_format"] = "ADC: {0}",
        ["monitor_speed_title"] = "Velocidad",
        ["monitor_speed_unit"] = "mm/s",
        ["monitor_speed_format"] = "{0} mm/s",
        ["monitor_count_format"] = "{0}×",
        ["monitor_columns_one"] = "1 columna",
        ["monitor_columns_two"] = "2 columnas",
        ["monitor_columns_grid"] = "Cuadrícula",
        ["monitor_columns_one_short"] = "1 col.",
        ["monitor_columns_two_short"] = "2 col.",
        ["monitor_columns_grid_short"] = "Cuadr.",
        ["monitor_electrodes"] = "Electrodos",
        ["monitor_emd_ebpa"] = "AESP/AEPS",
        ["monitor_muscle"] = "Músculo",
        ["monitor_eos"] = "EE",
        ["monitor_hr_format"] = "FC {0}",
        ["monitor_tips"] = "Consejos",
        ["settings_tcp_ip_error"] = "Formato de dirección IP no válido",
        ["settings_tcp_port_error"] = "El puerto debe estar entre 0–65535",
        ["ecg_point_p_start"] = "Inicio P",
        ["ecg_point_p_peak"] = "Pico P",
        ["ecg_point_p_end"] = "Fin P",
        ["ecg_point_q_peak"] = "Pico Q",
        ["ecg_point_r_peak"] = "Pico R",
        ["ecg_point_s_peak"] = "Pico S",
        ["ecg_point_qrs_start"] = "Inicio QRS",
        ["ecg_point_qrs_end"] = "Fin QRS",
        ["ecg_point_t_start"] = "Inicio T",
        ["ecg_point_t_peak"] = "Pico T",
        ["ecg_point_t_end"] = "Fin T",
        ["ecg_interval_p"] = "P",
        ["ecg_interval_qrs"] = "QRS",
        ["ecg_interval_t"] = "T",
        ["ecg_interval_pr"] = "PR",
        ["ecg_interval_st"] = "ST",
        ["ecg_interval_qt"] = "QT",
        ["ecg_interval_rr"] = "R-R",
        ["ecg_rr_value_format"] = "R-R: {0:0.000} s",
    };
}
