using CardioSimulator.Core.Domain;

namespace CardioSimulator.App.Localization;

/// <summary>
/// Language-aware UI strings, ported from the Android <c>res/values*/strings.xml</c>.
/// <see cref="Current"/> selects the active language; <see cref="Changed"/> fires when it
/// switches so the UI can re-pull localized text. Unknown keys fall back to English.
/// </summary>
public static class AppStrings
{
    private static Language _current = Language.EN;

    /// <summary>Raised when <see cref="Current"/> changes (UI rebuilds on this).</summary>
    public static event Action? Changed;

    public static Language Current
    {
        get => _current;
        set
        {
            if (_current == value) return;
            _current = value;
            Changed?.Invoke();
        }
    }

    private static string S(string key)
    {
        var table = _current switch
        {
            Language.RU => Ru,
            Language.ZH => Zh,
            Language.ES => Es,
            _ => En,
        };
        if (table.TryGetValue(key, out var value)) return value;
        return En.TryGetValue(key, out var en) ? en : key;
    }

    // Data source
    public static string DataSourceTitle => S("data_source_title");
    public static string DataSourceDescription => S("data_source_description");
    public static string DataSourcePickFolder => S("data_source_pick_folder");
    public static string DataSourceChangeFolder => S("data_source_change_folder");
    public static string DataSourceLoading => S("data_source_loading");
    public static string DataSourceContinue => S("data_source_continue");
    public static string DataSourceRetry => S("data_source_retry");
    public static string DataSourceShowDetails => S("data_source_show_details");
    public static string DataSourceClose => S("data_source_close");
    public static string DataSourceErrorBadManifest => S("data_source_error_bad_manifest");
    public static string DataSourceErrorUnreadable => S("data_source_error_unreadable");
    public static string DataSourceErrorEmpty => S("data_source_error_empty");
    public static string DataSourceExportZip => S("data_source_export_zip");
    public static string CourseDataTitle => S("course_data_title");
    public static string CourseChangeZip => S("course_change_zip");
    public static string CourseExportZip => S("course_export_zip");
    public static string RhythmSearchPlaceholder => S("rhythm_search_placeholder");
    public static string RhythmCourseFilterAll => S("rhythm_course_filter_all");
    public static string LectureSelectorTitle => S("lecture_selector_title");
    public static string FixDrawer => S("fix_drawer");

    // First-launch welcome screen
    public static string WelcomeTitle => S("welcome_title");
    public static string WelcomeBody => S("welcome_body");
    public static string WelcomeTagline => S("welcome_tagline");
    public static string WelcomeStart => S("welcome_start");
    public static IReadOnlyList<string> WelcomeFeatures => new[]
    {
        S("welcome_feature_1"),
        S("welcome_feature_2"),
        S("welcome_feature_3"),
        S("welcome_feature_4"),
    };

    // Rhythm list grouping ("all rhythms" mode)
    public static string PathologyGroupName(string key) => S("group_" + key);
    public static string RhythmSortByGroup => S("rhythm_sort_by_group");
    public static string RhythmSortAlphabetical => S("rhythm_sort_az");
    public static string RhythmGroupOther => S("group_other");

    // OSCE (ОСКЭ) station
    public static string OskeTabExam => S("oske_tab_exam");
    public static string OskeTabResults => S("oske_tab_results");
    public static string OskeTabConstructor => S("oske_tab_constructor");
    public static string OskeStart => S("oske_start");
    public static string OskeStartTitle => S("oske_start_title");
    public static string OskeIntro => S("oske_intro");
    public static string OskeFieldFullName => S("oske_field_full_name");
    public static string OskeFieldGroup => S("oske_field_group");
    public static string OskeFieldSpecialty => S("oske_field_specialty");
    public static string OskeFieldEcg => S("oske_field_ecg");
    public static string OskeSpecialtyTherapy => S("oske_specialty_therapy");
    public static string OskeSpecialtyCardiology => S("oske_specialty_cardiology");
    public static string OskeSpecialtyFd => S("oske_specialty_fd");
    public static string OskeNoEcgs => S("oske_no_ecgs");
    public static string OskeFinish => S("oske_finish");
    public static string OskeFinishConfirmTitle => S("oske_finish_confirm_title");
    public static string OskeFinishConfirm => S("oske_finish_confirm");
    public static string OskeResultTitle => S("oske_result_title");
    public static string OskePassed => S("oske_passed");
    public static string OskeFailed => S("oske_failed");
    public static string OskeNewAttempt => S("oske_new_attempt");
    public static string OskeUnanswered => S("oske_unanswered");
    public static string OskeResultsEmpty => S("oske_results_empty");
    public static string OskeComingSoon => S("oske_coming_soon");
    public static string OskeCtorSave => S("oske_ctor_save");
    public static string OskeCtorSaved => S("oske_ctor_saved");
    public static string OskeCtorIntro => S("oske_ctor_intro");
    public static string OskeCtorHasKey => S("oske_ctor_has_key");
    public static string OskeCtorModeKeys => S("oske_ctor_mode_keys");
    public static string OskeCtorModeForm => S("oske_ctor_mode_form");
    public static string OskeFormPass => S("oske_form_pass");
    public static string OskeFormAddQuestion => S("oske_form_add_question");
    public static string OskeFormAddOption => S("oske_form_add_option");
    public static string OskeFormSave => S("oske_form_save");
    public static string OskeFormSaved => S("oske_form_saved");
    public static string OskeFormSingle => S("oske_form_single");
    public static string OskeFormMulti => S("oske_form_multi");
    public static string OskeFormBlockTitle => S("oske_form_block_title");
    public static string OskeFormOption => S("oske_form_option");
    public static string OskeScoreFormat(int correct, int total) => string.Format(S("oske_score_format"), correct, total);

    // Self-assessment («Тестирование») + Test Constructor
    public static string TestSelectTitle => S("test_select_title");
    public static string TestStart => S("test_start");
    public static string TestEmpty => S("test_empty");
    public static string TestCounterFormat(int current, int total) => string.Format(S("test_counter_format"), current, total);
    public static string TestQuestionTitleFormat(int number) => string.Format(S("test_question_title_format"), number);
    public static string TestCommentTitle => S("test_comment_title");
    public static string TestCorrectAnswerFormat(int number) => string.Format(S("test_correct_answer_format"), number);
    public static string TestNext => S("test_next");
    public static string TestFinish => S("test_finish");
    public static string TestTimeUp => S("test_time_up");
    public static string TestResultTitle => S("test_result_title");
    public static string TestResultScoreFormat(int correct, int total) => string.Format(S("test_result_score_format"), correct, total);
    public static string TestRestart => S("test_restart");
    public static string TestCtorIntro => S("test_ctor_intro");
    public static string TestCtorNew => S("test_ctor_new");
    public static string TestCtorNewTitle => S("test_ctor_new_title");
    public static string TestCtorTitleLabel => S("test_ctor_title_label");
    public static string TestCtorTimeLabel => S("test_ctor_time_label");
    public static string TestCtorDelete => S("test_ctor_delete");
    public static string TestCtorDeleteConfirm => S("test_ctor_delete_confirm");
    public static string TestCtorSave => S("test_ctor_save");
    public static string TestCtorSaved => S("test_ctor_saved");
    public static string TestCtorAddQuestion => S("test_ctor_add_question");
    public static string TestCtorRemoveQuestion => S("test_ctor_remove_question");
    public static string TestCtorQuestionLabelFormat(int number) => string.Format(S("test_ctor_question_label_format"), number);
    public static string TestCtorQuestionText => S("test_ctor_question_text");
    public static string TestCtorOptionFormat(int number) => string.Format(S("test_ctor_option_format"), number);
    public static string TestCtorCorrect => S("test_ctor_correct");
    public static string TestCtorComment => S("test_ctor_comment");
    public static string TestCtorEcg => S("test_ctor_ecg");
    public static string TestCtorEcgNone => S("test_ctor_ecg_none");
    public static string TestCtorTestsLabel => S("test_ctor_tests_label");

    // Examination («Экзамен») — reuses the test bank, OSCE-style stored results
    public static string ExamTabExam => S("exam_tab_exam");
    public static string ExamTabResults => S("exam_tab_results");
    public static string ExamStart => S("exam_start");
    public static string ExamStartTitle => S("exam_start_title");
    public static string ExamIntro => S("exam_intro");
    public static string ExamFieldFullName => S("exam_field_full_name");
    public static string ExamFieldGroup => S("exam_field_group");
    public static string ExamFieldTest => S("exam_field_test");
    public static string ExamNoTests => S("exam_no_tests");
    public static string ExamFinish => S("exam_finish");
    public static string ExamFinishConfirmTitle => S("exam_finish_confirm_title");
    public static string ExamFinishConfirm => S("exam_finish_confirm");
    public static string ExamPassed => S("exam_passed");
    public static string ExamFailed => S("exam_failed");
    public static string ExamScoreFormat(int correct, int total) => string.Format(S("exam_score_format"), correct, total);
    public static string ExamNewAttempt => S("exam_new_attempt");
    public static string ExamUnanswered => S("exam_unanswered");
    public static string ExamResultsEmpty => S("exam_results_empty");

    public static string DataSourceLoadedFormat(int count) => string.Format(S("data_source_loaded_format"), count);
    public static string DataSourcePathologiesTitle(int count) => string.Format(S("data_source_pathologies_title"), count);

    // Settings
    public static string SettingsTitle => S("settings_title");
    public static string SettingsBlankSheet => S("settings_blank_sheet");
    public static string ModeCourseConstructor => S("mode_course_constructor");
    public static string CompareButton => S("compare_button");
    public static string CalcDerivedLeads => S("calc_derived_leads");
    public static string CompareSelectPathologies => S("compare_select_pathologies");
    public static string ComparePresets => S("compare_presets");
    public static string CompareSavePresetLabel => S("compare_save_preset_label");
    public static string CompareSavePresetPlaceholder => S("compare_save_preset_placeholder");
    public static string CompareModeTitle => S("compare_mode_title");
    public static string ComparePlaceholder => S("compare_placeholder");
    public static string CompareLeadLabel => S("compare_lead_label");
    public static string CompareExit => S("compare_exit");
    public static string CompareStartNew => S("compare_start_new");
    public static string CompareApplyPreset => S("compare_apply_preset");
    public static string CompareTargetTitle => S("compare_target_title");
    public static string CommonOk => S("common_ok");
    public static string CommonCancel => S("common_cancel");
    public static string CommonSave => S("common_save");
    public static string SettingsClose => S("settings_close");
    public static string SettingsColorScheme => S("settings_color_scheme");
    public static string ThemeLight => S("theme_light");
    public static string ThemeDark => S("theme_dark");
    public static string SettingsGridScheme => S("settings_grid_scheme");
    public static string GridSchemeBlank => S("grid_scheme_blank");
    public static string SettingsLanguage => S("settings_language");
    public static string SettingsTcpTitle => S("settings_tcp_title");
    public static string SettingsTcpIp => S("settings_tcp_ip");
    public static string SettingsTcpPort => S("settings_tcp_port");
    public static string TcpConnect => S("tcp_connect");
    public static string TcpDisconnect => S("tcp_disconnect");
    public static string TcpStatusConnected => S("tcp_status_connected");
    public static string TcpStatusConnecting => S("tcp_status_waiting");
    public static string TcpStatusDisconnected => S("tcp_status_disconnected");
    public static string TcpStatusError => S("tcp_status_error");
    public static string SettingsTcpIpError => S("settings_tcp_ip_error");
    public static string SettingsTcpPortError => S("settings_tcp_port_error");

    // Significant points / ECG annotations
    public static string EcgIntervalP => S("ecg_interval_p");
    public static string EcgIntervalQrs => S("ecg_interval_qrs");
    public static string EcgIntervalT => S("ecg_interval_t");
    public static string EcgIntervalPr => S("ecg_interval_pr");
    public static string EcgIntervalSt => S("ecg_interval_st");
    public static string EcgIntervalQt => S("ecg_interval_qt");
    public static string EcgIntervalRr => S("ecg_interval_rr");
    public static string EcgRrValueFormat(double seconds) => string.Format(S("ecg_rr_value_format"), seconds);
    public static string EditorSignificantPoints => S("editor_significant_points");
    public static string EditorPWave => S("editor_p_wave");
    public static string EditorQrsComplex => S("editor_qrs_complex");
    public static string EditorTWave => S("editor_t_wave");
    public static string EditorSelectPointHint => S("editor_select_point_hint");
    public static string EditorRhythmsTitle => S("editor_rhythms_title");
    public static string EditorSampleLabel(int index) => string.Format(S("editor_sample_label"), index);
    public static string EditorSetTimeTitle => S("editor_set_time_title");
    public static string EditorTimeUnit => S("editor_time_unit");
    public static string EditorTimeFormat(int ms) => string.Format(S("editor_time_format"), ms);
    public static string EditorSetAdcTitle => S("editor_set_adc_title");
    public static string EditorAdcLabel => S("editor_adc_label");
    public static string EditorAdcFormat(string value) => string.Format(S("editor_adc_format"), value);
    public static string MonitorSpeedTitle => S("monitor_speed_title");
    public static string MonitorSpeedUnit => S("monitor_speed_unit");
    public static string MonitorSpeedFormat(int speed) => string.Format(S("monitor_speed_format"), speed);
    public static string MonitorCountFormat(int count) => string.Format(S("monitor_count_format"), count);
    public static string MonitorColumnsOne => S("monitor_columns_one");
    public static string MonitorColumnsTwo => S("monitor_columns_two");
    public static string MonitorColumnsGrid => S("monitor_columns_grid");
    public static string MonitorColumnsOneShort => S("monitor_columns_one_short");
    public static string MonitorColumnsTwoShort => S("monitor_columns_two_short");
    public static string MonitorColumnsGridShort => S("monitor_columns_grid_short");
    public static string EcgOpenMonitor => S("ecg_open_monitor");
    public static string MonitorElectrodes => S("monitor_electrodes");
    public static string MonitorEmdEbpa => S("monitor_emd_ebpa");
    public static string MonitorMuscle => S("monitor_muscle");
    public static string MonitorEos => S("monitor_eos");
    public static string MonitorHrFormat(int hr) => string.Format(S("monitor_hr_format"), hr);
    public static string MonitorTips => S("monitor_tips");

    public static string EcgPointLabel(EcgPointType type) => S(type switch
    {
        EcgPointType.P_START => "ecg_point_p_start",
        EcgPointType.P_PEAK => "ecg_point_p_peak",
        EcgPointType.P_END => "ecg_point_p_end",
        EcgPointType.Q_PEAK => "ecg_point_q_peak",
        EcgPointType.R_PEAK => "ecg_point_r_peak",
        EcgPointType.S_PEAK => "ecg_point_s_peak",
        EcgPointType.QRS_START => "ecg_point_qrs_start",
        EcgPointType.QRS_END => "ecg_point_qrs_end",
        EcgPointType.T_START => "ecg_point_t_start",
        EcgPointType.T_PEAK => "ecg_point_t_peak",
        EcgPointType.T_END => "ecg_point_t_end",
        _ => "ecg_point_p_peak",
    });

    public static string ModeName(OperatingMode mode) => S(mode.TitleResourceKey());
    public static string GridSchemeLabel(GridScheme scheme) => S(scheme.LabelResourceKey());

    private static readonly Dictionary<string, string> En = new()
    {
        ["data_source_title"] = "ECG Data",
        ["data_source_description"] = "Select a ZIP archive on your device containing the ECG data.",
        ["data_source_pick_folder"] = "Select ZIP archive",
        ["data_source_change_folder"] = "Change ZIP archive",
        ["data_source_loading"] = "Loading data…",
        ["data_source_continue"] = "Continue",
        ["data_source_retry"] = "Pick another ZIP",
        ["data_source_show_details"] = "Show Details",
        ["data_source_close"] = "Close",
        ["data_source_error_bad_manifest"] = "The ZIP archive contains an invalid or missing manifest file.",
        ["data_source_error_unreadable"] = "The selected ZIP archive is no longer accessible.",
        ["data_source_error_empty"] = "No ECG files were found in the selected ZIP archive.",
        ["data_source_export_zip"] = "Export ZIP",
        ["course_data_title"] = "Course Data",
        ["course_change_zip"] = "Change Courses ZIP",
        ["course_export_zip"] = "Export Courses ZIP",
        ["data_source_loaded_format"] = "Loaded {0} pathologies",
        ["data_source_pathologies_title"] = "Loaded Pathologies ({0})",
        ["rhythm_search_placeholder"] = "Rhythm…",
        ["rhythm_course_filter_all"] = "All rhythms",
        ["lecture_selector_title"] = "Lecture",
        ["mode_course_constructor"] = "Course Constructor",
        ["mode_oske_constructor"] = "OSCE Constructor",
        ["compare_button"] = "Compare",
        ["settings_blank_sheet"] = "Blank Sheet",
        ["calc_derived_leads"] = "Calc Derived Leads",
        ["compare_select_pathologies"] = "Select pathologies to overlay:",
        ["compare_presets"] = "Saved presets",
        ["compare_save_preset_label"] = "Save layout as preset:",
        ["compare_save_preset_placeholder"] = "Preset name…",
        ["compare_mode_title"] = "Compare mode",
        ["compare_placeholder"] = "Tap to add comparison",
        ["compare_lead_label"] = "Lead",
        ["compare_exit"] = "Exit comparison",
        ["compare_start_new"] = "New comparison",
        ["compare_apply_preset"] = "Apply preset",
        ["compare_target_title"] = "Select comparison",
        ["common_ok"] = "OK",
        ["common_cancel"] = "Cancel",
        ["common_save"] = "Save",
        ["settings_title"] = "Settings",
        ["settings_close"] = "CLOSE",
        ["settings_color_scheme"] = "App Theme",
        ["theme_light"] = "Light",
        ["theme_dark"] = "Dark",
        ["settings_grid_scheme"] = "Monitor Grid Scheme",
        ["settings_language"] = "Language",
        ["settings_tcp_title"] = "TCP Connection",
        ["settings_tcp_ip"] = "IP Address",
        ["settings_tcp_port"] = "Port",
        ["tcp_connect"] = "Connect",
        ["tcp_disconnect"] = "Disconnect",
        ["tcp_status_connected"] = "Connected",
        ["tcp_status_waiting"] = "Waiting…",
        ["tcp_status_disconnected"] = "Disconnected",
        ["tcp_status_error"] = "Error",
        ["mode_teaching"] = "Teaching",
        ["mode_testing"] = "Testing",
        ["mode_test_constructor"] = "Test Constructor",
        ["test_select_title"] = "Test",
        ["test_start"] = "Start test",
        ["test_empty"] = "No tests yet. Create one in the Test Constructor.",
        ["test_counter_format"] = "{0} of {1}",
        ["test_question_title_format"] = "Question {0}",
        ["test_comment_title"] = "Comment",
        ["test_correct_answer_format"] = "Correct answer: {0}",
        ["test_next"] = "Next question",
        ["test_finish"] = "Finish",
        ["test_time_up"] = "Time's up",
        ["test_result_title"] = "Test complete",
        ["test_result_score_format"] = "Result: {0} of {1}",
        ["test_restart"] = "Restart",
        ["test_ctor_intro"] = "Select a test to edit, or create a new one.",
        ["test_ctor_new"] = "New test",
        ["test_ctor_new_title"] = "New test",
        ["test_ctor_title_label"] = "Test title",
        ["test_ctor_time_label"] = "Seconds per question (0 = untimed)",
        ["test_ctor_delete"] = "Delete",
        ["test_ctor_delete_confirm"] = "Delete this test?",
        ["test_ctor_save"] = "Save",
        ["test_ctor_saved"] = "Saved",
        ["test_ctor_add_question"] = "Add question",
        ["test_ctor_remove_question"] = "Remove question",
        ["test_ctor_question_label_format"] = "Question {0}",
        ["test_ctor_question_text"] = "Question text",
        ["test_ctor_option_format"] = "Option {0}",
        ["test_ctor_correct"] = "Correct",
        ["test_ctor_comment"] = "Comment (shown after answering)",
        ["test_ctor_ecg"] = "ECG on the monitor",
        ["test_ctor_ecg_none"] = "— none —",
        ["test_ctor_tests_label"] = "Tests",
        ["exam_tab_exam"] = "Exam",
        ["exam_tab_results"] = "Results",
        ["exam_start"] = "Start exam",
        ["exam_start_title"] = "Start examination",
        ["exam_intro"] = "Enter your details and choose a test to begin the examination.",
        ["exam_field_full_name"] = "Full name",
        ["exam_field_group"] = "Group",
        ["exam_field_test"] = "Test",
        ["exam_no_tests"] = "No tests available. Create one in the Test Constructor.",
        ["exam_finish"] = "Finish",
        ["exam_finish_confirm_title"] = "Finish examination?",
        ["exam_finish_confirm"] = "Submit your answers for grading? This cannot be undone.",
        ["exam_passed"] = "Passed",
        ["exam_failed"] = "Failed",
        ["exam_score_format"] = "{0} of {1}",
        ["exam_new_attempt"] = "New attempt",
        ["exam_unanswered"] = "Not answered",
        ["exam_results_empty"] = "No saved results yet.",
        ["mode_examination"] = "Examination",
        ["mode_oske"] = "OSKE",
        ["mode_editor"] = "Constructor ECG",
        ["oske_tab_exam"] = "Exam",
        ["oske_tab_results"] = "Results",
        ["oske_tab_constructor"] = "Constructor",
        ["oske_start"] = "Start OSCE",
        ["oske_start_title"] = "Start station",
        ["oske_intro"] = "Enter your details and choose an ECG to begin the station.",
        ["oske_field_full_name"] = "Full name",
        ["oske_field_group"] = "Group",
        ["oske_field_specialty"] = "Specialty",
        ["oske_field_ecg"] = "ECG",
        ["oske_specialty_therapy"] = "Therapy",
        ["oske_specialty_cardiology"] = "Cardiology",
        ["oske_specialty_fd"] = "Functional diagnostics",
        ["oske_no_ecgs"] = "No ECGs with reference answers for this specialty yet. Author them in the OSCE constructor.",
        ["oske_finish"] = "Finish",
        ["oske_finish_confirm_title"] = "Finish the attempt?",
        ["oske_finish_confirm"] = "Submit your answers for grading? This cannot be changed afterwards.",
        ["oske_result_title"] = "Result",
        ["oske_passed"] = "Passed",
        ["oske_failed"] = "Not passed",
        ["oske_new_attempt"] = "New attempt",
        ["oske_unanswered"] = "Not answered",
        ["oske_results_empty"] = "No saved results yet.",
        ["oske_coming_soon"] = "Coming in a later update.",
        ["oske_ctor_save"] = "Save key",
        ["oske_ctor_saved"] = "Saved ✓",
        ["oske_ctor_intro"] = "Select a specialty and an ECG, then mark the correct answer(s) for each block.",
        ["oske_ctor_has_key"] = "✓ key exists",
        ["oske_ctor_mode_keys"] = "Reference answers",
        ["oske_ctor_mode_form"] = "Form template",
        ["oske_form_pass"] = "Pass threshold, %",
        ["oske_form_add_question"] = "Add block",
        ["oske_form_add_option"] = "Add option",
        ["oske_form_save"] = "Save form",
        ["oske_form_saved"] = "Form saved ✓",
        ["oske_form_single"] = "One answer",
        ["oske_form_multi"] = "Several answers",
        ["oske_form_block_title"] = "Block title",
        ["oske_form_option"] = "Option",
        ["oske_score_format"] = "{0} of {1} blocks correct",
        ["grid_scheme_pink"] = "Pink",
        ["grid_scheme_blue_gray"] = "Blue/Gray",
        ["grid_scheme_blank"] = "Blank",
        ["editor_significant_points"] = "Significant Points",
        ["editor_sample_label"] = "Sample: {0}",
        ["editor_p_wave"] = "P Wave",
        ["editor_qrs_complex"] = "QRS Complex",
        ["editor_t_wave"] = "T Wave",
        ["editor_select_point_hint"] = "Select a point on the chart to mark it",
        ["editor_rhythms_title"] = "Rhythms",
        ["fix_drawer"] = "Fix drawer",
        ["welcome_title"] = "Welcome to the world of ECG",
        ["welcome_body"] = "This simulator is here to answer all your ECG questions. Study rhythms and pathologies on a realistic monitor, work through interactive courses and lectures, test yourself, and even build your own ECGs and teaching materials.",
        ["welcome_feature_1"] = "Realistic 12-lead ECG monitor",
        ["welcome_feature_2"] = "Courses and lectures with interactive examples",
        ["welcome_feature_3"] = "Tests, exams and the OSCE station for self-assessment",
        ["welcome_feature_4"] = "Constructors for your own ECGs, courses and tests",
        ["welcome_tagline"] = "Let's get started!",
        ["welcome_start"] = "Start",
        ["rhythm_sort_by_group"] = "By groups",
        ["rhythm_sort_az"] = "Alphabetical (A–Z)",
        ["group_sinus"] = "Sinus",
        ["group_arrhythmia"] = "Rhythm disturbances",
        ["group_conduction"] = "Conduction disturbances",
        ["group_hypertrophy"] = "Myocardial hypertrophy",
        ["group_ischemia"] = "Ischemia",
        ["group_infarction"] = "Infarction",
        ["group_electrolyte"] = "Electrolyte disturbances and toxic effects",
        ["group_syndromes"] = "Syndromes, channelopathies and specific conditions",
        ["group_pacemaker"] = "Artificial pacemakers",
        ["group_special"] = "Special patient groups and differential diagnosis",
        ["group_pediatric"] = "Pediatric ECG",
        ["group_newborn"] = "Newborn ECG",
        ["group_pregnant"] = "ECG in pregnancy",
        ["group_other"] = "Other",
        ["editor_set_time_title"] = "Set Time (ms)",
        ["editor_time_unit"] = "ms",
        ["editor_time_format"] = "{0} ms",
        ["editor_set_adc_title"] = "Set ADC Value",
        ["editor_adc_label"] = "ADC",
        ["editor_adc_format"] = "ADC: {0}",
        ["monitor_speed_title"] = "Speed",
        ["monitor_speed_unit"] = "mm/s",
        ["monitor_speed_format"] = "{0} mm/s",
        ["monitor_count_format"] = "{0}×",
        ["monitor_columns_one"] = "1 Column",
        ["monitor_columns_two"] = "2 Columns",
        ["monitor_columns_grid"] = "Grid",
        ["monitor_columns_one_short"] = "1 Col",
        ["monitor_columns_two_short"] = "2 Cols",
        ["monitor_columns_grid_short"] = "Grid",
        ["ecg_open_monitor"] = "Open on monitor",
        ["monitor_electrodes"] = "Electrodes",
        ["monitor_emd_ebpa"] = "EMD/EBPA",
        ["monitor_muscle"] = "Muscle",
        ["monitor_eos"] = "EOS",
        ["monitor_hr_format"] = "HR {0}",
        ["monitor_tips"] = "Tips",
        ["settings_tcp_ip_error"] = "Invalid IP Address format",
        ["settings_tcp_port_error"] = "Port must be 0–65535",
        ["ecg_point_p_start"] = "P Start",
        ["ecg_point_p_peak"] = "P Peak",
        ["ecg_point_p_end"] = "P End",
        ["ecg_point_q_peak"] = "Q Peak",
        ["ecg_point_r_peak"] = "R Peak",
        ["ecg_point_s_peak"] = "S Peak",
        ["ecg_point_qrs_start"] = "QRS Start",
        ["ecg_point_qrs_end"] = "QRS End",
        ["ecg_point_t_start"] = "T Start",
        ["ecg_point_t_peak"] = "T Peak",
        ["ecg_point_t_end"] = "T End",
        ["ecg_interval_p"] = "P",
        ["ecg_interval_qrs"] = "QRS",
        ["ecg_interval_t"] = "T",
        ["ecg_interval_pr"] = "PR",
        ["ecg_interval_st"] = "ST",
        ["ecg_interval_qt"] = "QT",
        ["ecg_interval_rr"] = "R-R",
        ["ecg_rr_value_format"] = "R-R: {0:0.000} s",
    };

    private static readonly Dictionary<string, string> Ru = new()
    {
        ["data_source_title"] = "Данные ЭКГ",
        ["data_source_description"] = "Выберите на устройстве ZIP-архив, содержащий данные ЭКГ.",
        ["data_source_pick_folder"] = "Выбрать ZIP-архив",
        ["data_source_change_folder"] = "Сменить ZIP-архив",
        ["data_source_loading"] = "Загрузка данных…",
        ["data_source_continue"] = "Продолжить",
        ["data_source_retry"] = "Выбрать другой архив",
        ["data_source_show_details"] = "Подробнее",
        ["data_source_close"] = "Закрыть",
        ["data_source_error_bad_manifest"] = "ZIP-архив содержит неверный или отсутствующий файл манифеста.",
        ["data_source_error_unreadable"] = "Выбранный архив больше недоступен.",
        ["data_source_error_empty"] = "В выбранном архиве не найдены файлы ЭКГ.",
        ["data_source_export_zip"] = "Экспорт ZIP",
        ["course_data_title"] = "Данные курсов",
        ["course_change_zip"] = "Сменить ZIP курсов",
        ["course_export_zip"] = "Экспорт ZIP курсов",
        ["data_source_loaded_format"] = "Загружено патологий: {0}",
        ["data_source_pathologies_title"] = "Загруженные патологии ({0})",
        ["rhythm_search_placeholder"] = "Ритм…",
        ["rhythm_course_filter_all"] = "Все ритмы",
        ["lecture_selector_title"] = "Лекция",
        ["mode_course_constructor"] = "Конструктор курсов",
        ["mode_oske_constructor"] = "Конструктор ОСКЭ",
        ["compare_button"] = "Сравнение",
        ["settings_blank_sheet"] = "Чистый лист",
        ["calc_derived_leads"] = "Рассчитать отведения",
        ["compare_select_pathologies"] = "Выберите патологии для наложения:",
        ["compare_presets"] = "Сохранённые пресеты",
        ["compare_save_preset_label"] = "Сохранить раскладку как пресет:",
        ["compare_save_preset_placeholder"] = "Название пресета…",
        ["compare_mode_title"] = "Режим сравнения",
        ["compare_placeholder"] = "Нажмите, чтобы добавить",
        ["compare_lead_label"] = "Отведение",
        ["compare_exit"] = "Выйти из сравнения",
        ["compare_start_new"] = "Новое сравнение",
        ["compare_apply_preset"] = "Применить пресет",
        ["compare_target_title"] = "Выбор сравнения",
        ["common_ok"] = "ОК",
        ["common_cancel"] = "Отмена",
        ["common_save"] = "Сохранить",
        ["settings_title"] = "Настройки",
        ["settings_close"] = "ЗАКРЫТЬ",
        ["settings_color_scheme"] = "Тема приложения",
        ["theme_light"] = "Светлая",
        ["theme_dark"] = "Темная",
        ["settings_grid_scheme"] = "Сетка монитора",
        ["settings_language"] = "Язык",
        ["settings_tcp_title"] = "TCP соединение",
        ["settings_tcp_ip"] = "IP-адрес",
        ["settings_tcp_port"] = "Порт",
        ["tcp_connect"] = "Подключить",
        ["tcp_disconnect"] = "Отключить",
        ["tcp_status_connected"] = "Подключено",
        ["tcp_status_waiting"] = "Ожидание…",
        ["tcp_status_disconnected"] = "Отключено",
        ["tcp_status_error"] = "Ошибка",
        ["mode_teaching"] = "Обучение",
        ["mode_testing"] = "Тестирование",
        ["mode_test_constructor"] = "Конструктор тестов",
        ["test_select_title"] = "Тест",
        ["test_start"] = "Начать тест",
        ["test_empty"] = "Тестов пока нет. Создайте тест в конструкторе тестов.",
        ["test_counter_format"] = "{0} из {1}",
        ["test_question_title_format"] = "{0} вопрос",
        ["test_comment_title"] = "Комментарий",
        ["test_correct_answer_format"] = "Правильный ответ: {0}",
        ["test_next"] = "Следующий вопрос",
        ["test_finish"] = "Завершить",
        ["test_time_up"] = "Время вышло",
        ["test_result_title"] = "Тест завершён",
        ["test_result_score_format"] = "Результат: {0} из {1}",
        ["test_restart"] = "Пройти заново",
        ["test_ctor_intro"] = "Выберите тест для редактирования или создайте новый.",
        ["test_ctor_new"] = "Новый тест",
        ["test_ctor_new_title"] = "Новый тест",
        ["test_ctor_title_label"] = "Название теста",
        ["test_ctor_time_label"] = "Секунд на вопрос (0 — без таймера)",
        ["test_ctor_delete"] = "Удалить",
        ["test_ctor_delete_confirm"] = "Удалить этот тест?",
        ["test_ctor_save"] = "Сохранить",
        ["test_ctor_saved"] = "Сохранено",
        ["test_ctor_add_question"] = "Добавить вопрос",
        ["test_ctor_remove_question"] = "Удалить вопрос",
        ["test_ctor_question_label_format"] = "Вопрос {0}",
        ["test_ctor_question_text"] = "Текст вопроса",
        ["test_ctor_option_format"] = "Вариант {0}",
        ["test_ctor_correct"] = "Верный",
        ["test_ctor_comment"] = "Комментарий (показывается после ответа)",
        ["test_ctor_ecg"] = "ЭКГ на мониторе",
        ["test_ctor_ecg_none"] = "— нет —",
        ["test_ctor_tests_label"] = "Тесты",
        ["exam_tab_exam"] = "Экзамен",
        ["exam_tab_results"] = "Результаты",
        ["exam_start"] = "Начать экзамен",
        ["exam_start_title"] = "Начало экзамена",
        ["exam_intro"] = "Введите свои данные и выберите тест, чтобы начать экзамен.",
        ["exam_field_full_name"] = "ФИО",
        ["exam_field_group"] = "Группа",
        ["exam_field_test"] = "Тест",
        ["exam_no_tests"] = "Нет доступных тестов. Создайте тест в конструкторе тестов.",
        ["exam_finish"] = "Завершить",
        ["exam_finish_confirm_title"] = "Завершить экзамен?",
        ["exam_finish_confirm"] = "Отправить ответы на проверку? Отменить будет нельзя.",
        ["exam_passed"] = "Сдано",
        ["exam_failed"] = "Не сдано",
        ["exam_score_format"] = "{0} из {1}",
        ["exam_new_attempt"] = "Новая попытка",
        ["exam_unanswered"] = "Нет ответа",
        ["exam_results_empty"] = "Сохранённых результатов пока нет.",
        ["mode_examination"] = "Экзамен",
        ["mode_oske"] = "ОСКЭ",
        ["oske_tab_exam"] = "Экзамен",
        ["oske_tab_results"] = "Результаты",
        ["oske_tab_constructor"] = "Конструктор",
        ["oske_start"] = "Начать ОСКЭ",
        ["oske_start_title"] = "Начало станции",
        ["oske_intro"] = "Введите свои данные и выберите ЭКГ, чтобы начать станцию.",
        ["oske_field_full_name"] = "ФИО",
        ["oske_field_group"] = "Группа",
        ["oske_field_specialty"] = "Специальность",
        ["oske_field_ecg"] = "ЭКГ",
        ["oske_specialty_therapy"] = "Терапия",
        ["oske_specialty_cardiology"] = "Кардиология",
        ["oske_specialty_fd"] = "Функциональная диагностика",
        ["oske_no_ecgs"] = "Пока нет ЭКГ с эталонными ответами для этой специальности. Задайте их в конструкторе ОСКЭ.",
        ["oske_finish"] = "Завершить",
        ["oske_finish_confirm_title"] = "Завершить попытку?",
        ["oske_finish_confirm"] = "Отправить ответы на проверку? Изменить их потом будет нельзя.",
        ["oske_result_title"] = "Результат",
        ["oske_passed"] = "Зачёт",
        ["oske_failed"] = "Незачёт",
        ["oske_new_attempt"] = "Новая попытка",
        ["oske_unanswered"] = "Нет ответа",
        ["oske_results_empty"] = "Пока нет сохранённых результатов.",
        ["oske_coming_soon"] = "Появится в следующем обновлении.",
        ["oske_ctor_save"] = "Сохранить эталон",
        ["oske_ctor_saved"] = "Сохранено ✓",
        ["oske_ctor_intro"] = "Выберите специальность и ЭКГ, затем отметьте правильный(е) ответ(ы) для каждого блока.",
        ["oske_ctor_has_key"] = "✓ эталон задан",
        ["oske_ctor_mode_keys"] = "Эталоны ответов",
        ["oske_ctor_mode_form"] = "Шаблон формы",
        ["oske_form_pass"] = "Проходной балл, %",
        ["oske_form_add_question"] = "Добавить блок",
        ["oske_form_add_option"] = "Добавить вариант",
        ["oske_form_save"] = "Сохранить форму",
        ["oske_form_saved"] = "Форма сохранена ✓",
        ["oske_form_single"] = "Один ответ",
        ["oske_form_multi"] = "Несколько ответов",
        ["oske_form_block_title"] = "Заголовок блока",
        ["oske_form_option"] = "Вариант",
        ["oske_score_format"] = "Верно {0} из {1} блоков",
        ["mode_editor"] = "Конструктор ЭКГ",
        ["grid_scheme_pink"] = "Розовая",
        ["grid_scheme_blue_gray"] = "Сине-серая",
        ["grid_scheme_blank"] = "Чистый лист",
        ["editor_significant_points"] = "Значимые точки",
        ["editor_sample_label"] = "Точка: {0}",
        ["editor_p_wave"] = "Зубец P",
        ["editor_qrs_complex"] = "Комплекс QRS",
        ["editor_t_wave"] = "Зубец T",
        ["editor_select_point_hint"] = "Выберите точку на графике, чтобы отметить ее",
        ["editor_rhythms_title"] = "Ритмы",
        ["fix_drawer"] = "Закрепить панель",
        ["welcome_title"] = "Добро пожаловать в мир ЭКГ",
        ["welcome_body"] = "В этом симуляторе вы найдёте ответы на все ваши вопросы по ЭКГ. Изучайте ритмы и патологии на реалистичном мониторе, проходите интерактивные курсы и лекции, проверяйте себя и создавайте собственные ЭКГ и учебные материалы.",
        ["welcome_feature_1"] = "Реалистичный монитор ЭКГ на 12 отведений",
        ["welcome_feature_2"] = "Курсы и лекции с интерактивными примерами",
        ["welcome_feature_3"] = "Тесты, экзамены и станция ОСКЭ для самопроверки",
        ["welcome_feature_4"] = "Конструкторы собственных ЭКГ, курсов и тестов",
        ["welcome_tagline"] = "Давайте начнём!",
        ["welcome_start"] = "Начать",
        ["rhythm_sort_by_group"] = "По группам",
        ["rhythm_sort_az"] = "По алфавиту (А–Я)",
        ["group_sinus"] = "Синусовый",
        ["group_arrhythmia"] = "Нарушения ритма",
        ["group_conduction"] = "Нарушения проводимости",
        ["group_hypertrophy"] = "Гипертрофия миокарда",
        ["group_ischemia"] = "Ишемия",
        ["group_infarction"] = "Инфаркт",
        ["group_electrolyte"] = "Электролитные нарушения и токсические эффекты",
        ["group_syndromes"] = "Синдромы, каналопатии и специфические состояния",
        ["group_pacemaker"] = "Искусственные водители ритма",
        ["group_special"] = "Особые группы пациентов и дифференциальная диагностика",
        ["group_pediatric"] = "Педиатрическая ЭКГ",
        ["group_newborn"] = "ЭКГ у новорождённых",
        ["group_pregnant"] = "ЭКГ у беременных",
        ["group_other"] = "Прочее",
        ["editor_set_time_title"] = "Установить время (мс)",
        ["editor_time_unit"] = "мс",
        ["editor_time_format"] = "{0} мс",
        ["editor_set_adc_title"] = "Установить значение АЦП",
        ["editor_adc_label"] = "АЦП",
        ["editor_adc_format"] = "АЦП: {0}",
        ["monitor_speed_title"] = "Скорость",
        ["monitor_speed_unit"] = "мм/с",
        ["monitor_speed_format"] = "{0} мм/с",
        ["monitor_count_format"] = "{0}×",
        ["monitor_columns_one"] = "1 столбец",
        ["monitor_columns_two"] = "2 столбца",
        ["monitor_columns_grid"] = "Сетка",
        ["monitor_columns_one_short"] = "1 ст.",
        ["monitor_columns_two_short"] = "2 ст.",
        ["monitor_columns_grid_short"] = "Сетка",
        ["ecg_open_monitor"] = "Открыть на мониторе",
        ["monitor_electrodes"] = "Электроды",
        ["monitor_emd_ebpa"] = "ЭМД/ЭБПА",
        ["monitor_muscle"] = "Мышцы",
        ["monitor_eos"] = "ЭОС",
        ["monitor_hr_format"] = "ЧСС {0}",
        ["monitor_tips"] = "Подсказки",
        ["settings_tcp_ip_error"] = "Неверный формат IP-адреса",
        ["settings_tcp_port_error"] = "Порт должен быть в диапазоне 0–65535",
        ["ecg_point_p_start"] = "P начало",
        ["ecg_point_p_peak"] = "P пик",
        ["ecg_point_p_end"] = "P конец",
        ["ecg_point_q_peak"] = "Q пик",
        ["ecg_point_r_peak"] = "R пик",
        ["ecg_point_s_peak"] = "S пик",
        ["ecg_point_qrs_start"] = "QRS начало",
        ["ecg_point_qrs_end"] = "QRS конец",
        ["ecg_point_t_start"] = "T начало",
        ["ecg_point_t_peak"] = "T пик",
        ["ecg_point_t_end"] = "T конец",
        ["ecg_interval_p"] = "P",
        ["ecg_interval_qrs"] = "QRS",
        ["ecg_interval_t"] = "T",
        ["ecg_interval_pr"] = "PR",
        ["ecg_interval_st"] = "ST",
        ["ecg_interval_qt"] = "QT",
        ["ecg_interval_rr"] = "R-R",
        ["ecg_rr_value_format"] = "R-R: {0:0.000} с",
    };

    private static readonly Dictionary<string, string> Zh = new()
    {
        ["data_source_title"] = "心电图数据",
        ["data_source_description"] = "请选择设备上包含心电图数据的 ZIP 压缩包。",
        ["data_source_pick_folder"] = "选择 ZIP 压缩包",
        ["data_source_change_folder"] = "更改 ZIP 压缩包",
        ["data_source_loading"] = "正在加载数据…",
        ["data_source_continue"] = "继续",
        ["data_source_retry"] = "选择其他 ZIP",
        ["data_source_show_details"] = "显示详情",
        ["data_source_close"] = "关闭",
        ["data_source_error_bad_manifest"] = "ZIP 压缩包包含无效或缺失的清单文件。",
        ["data_source_error_unreadable"] = "所选 ZIP 压缩包已无法访问。",
        ["data_source_error_empty"] = "所选 ZIP 压缩包中未找到心电图文件。",
        ["data_source_export_zip"] = "导出 ZIP",
        ["course_data_title"] = "课程数据",
        ["course_change_zip"] = "更改课程 ZIP",
        ["course_export_zip"] = "导出课程 ZIP",
        ["data_source_loaded_format"] = "已加载 {0} 个病理",
        ["data_source_pathologies_title"] = "已加载病理 ({0})",
        ["rhythm_search_placeholder"] = "心律…",
        ["rhythm_course_filter_all"] = "全部心律",
        ["lecture_selector_title"] = "讲座",
        ["settings_title"] = "设置",
        ["settings_close"] = "关闭",
        ["settings_color_scheme"] = "应用主题",
        ["theme_light"] = "浅色",
        ["theme_dark"] = "深色",
        ["settings_grid_scheme"] = "监视器网格方案",
        ["settings_language"] = "语言",
        ["settings_tcp_title"] = "TCP 连接",
        ["settings_tcp_ip"] = "IP 地址",
        ["settings_tcp_port"] = "端口",
        ["tcp_connect"] = "连接",
        ["tcp_disconnect"] = "断开连接",
        ["tcp_status_connected"] = "已连接",
        ["tcp_status_waiting"] = "等待中…",
        ["tcp_status_disconnected"] = "未连接",
        ["tcp_status_error"] = "错误",
        ["mode_teaching"] = "教学",
        ["mode_testing"] = "测试",
        ["mode_test_constructor"] = "测试构建器",
        ["test_select_title"] = "测试",
        ["test_start"] = "开始测试",
        ["test_empty"] = "暂无测试。请在测试构建器中创建。",
        ["test_counter_format"] = "{0} / {1}",
        ["test_question_title_format"] = "第 {0} 题",
        ["test_comment_title"] = "评注",
        ["test_correct_answer_format"] = "正确答案：{0}",
        ["test_next"] = "下一题",
        ["test_finish"] = "完成",
        ["test_time_up"] = "时间到",
        ["test_result_title"] = "测试完成",
        ["test_result_score_format"] = "结果：{0} / {1}",
        ["test_restart"] = "重新开始",
        ["test_ctor_intro"] = "选择要编辑的测试，或新建一个。",
        ["test_ctor_new"] = "新建测试",
        ["test_ctor_new_title"] = "新建测试",
        ["test_ctor_title_label"] = "测试标题",
        ["test_ctor_time_label"] = "每题秒数（0 = 不计时）",
        ["test_ctor_delete"] = "删除",
        ["test_ctor_delete_confirm"] = "删除此测试？",
        ["test_ctor_save"] = "保存",
        ["test_ctor_saved"] = "已保存",
        ["test_ctor_add_question"] = "添加题目",
        ["test_ctor_remove_question"] = "删除题目",
        ["test_ctor_question_label_format"] = "第 {0} 题",
        ["test_ctor_question_text"] = "题目内容",
        ["test_ctor_option_format"] = "选项 {0}",
        ["test_ctor_correct"] = "正确",
        ["test_ctor_comment"] = "评注（作答后显示）",
        ["test_ctor_ecg"] = "监视器上的心电图",
        ["test_ctor_ecg_none"] = "— 无 —",
        ["test_ctor_tests_label"] = "测试",
        ["exam_tab_exam"] = "考试",
        ["exam_tab_results"] = "结果",
        ["exam_start"] = "开始考试",
        ["exam_start_title"] = "开始考试",
        ["exam_intro"] = "请输入您的信息并选择一个测试以开始考试。",
        ["exam_field_full_name"] = "姓名",
        ["exam_field_group"] = "组别",
        ["exam_field_test"] = "测试",
        ["exam_no_tests"] = "暂无可用测试。请在测试构建器中创建。",
        ["exam_finish"] = "完成",
        ["exam_finish_confirm_title"] = "完成考试？",
        ["exam_finish_confirm"] = "提交答案进行评分？此操作无法撤销。",
        ["exam_passed"] = "通过",
        ["exam_failed"] = "未通过",
        ["exam_score_format"] = "{0} / {1}",
        ["exam_new_attempt"] = "新的尝试",
        ["exam_unanswered"] = "未作答",
        ["exam_results_empty"] = "暂无保存的结果。",
        ["mode_examination"] = "考试",
        ["mode_oske"] = "客观结构化临床考试",
        ["mode_editor"] = "心电图构建器",
        ["mode_course_constructor"] = "课程构建器",
        ["compare_button"] = "比较",
        ["compare_mode_title"] = "比较模式",
        ["compare_placeholder"] = "点击添加比较",
        ["compare_lead_label"] = "导联",
        ["compare_exit"] = "退出比较",
        ["compare_start_new"] = "新建比较",
        ["compare_apply_preset"] = "应用预设",
        ["compare_target_title"] = "选择比较",
        ["compare_presets"] = "已保存的预设",
        ["compare_save_preset_label"] = "将布局另存为预设：",
        ["compare_save_preset_placeholder"] = "预设名称…",
        ["common_ok"] = "确定",
        ["common_cancel"] = "取消",
        ["common_save"] = "保存",
        ["settings_blank_sheet"] = "空白页",
        ["calc_derived_leads"] = "计算衍生导联",
        ["grid_scheme_pink"] = "粉色",
        ["grid_scheme_blue_gray"] = "蓝灰色",
        ["grid_scheme_blank"] = "空白",
        ["editor_significant_points"] = "重要点",
        ["editor_sample_label"] = "样本: {0}",
        ["editor_p_wave"] = "P 波",
        ["editor_qrs_complex"] = "QRS 波群",
        ["editor_t_wave"] = "T 波",
        ["editor_select_point_hint"] = "在图表上选择一个点进行标记",
        ["editor_rhythms_title"] = "心律",
        ["fix_drawer"] = "固定面板",
        ["welcome_title"] = "欢迎来到心电图的世界",
        ["welcome_body"] = "本模拟器将为您解答关于心电图的所有疑问。在逼真的监视器上学习心律与病理，完成互动课程与讲座，进行自我检测，还能创建自己的心电图和教学资料。",
        ["welcome_feature_1"] = "逼真的 12 导联心电图监视器",
        ["welcome_feature_2"] = "包含互动示例的课程与讲座",
        ["welcome_feature_3"] = "用于自我评估的测验、考试和客观结构化临床考试站",
        ["welcome_feature_4"] = "心电图、课程和测试的构建器",
        ["welcome_tagline"] = "让我们开始吧！",
        ["welcome_start"] = "开始",
        ["rhythm_sort_by_group"] = "按分组",
        ["rhythm_sort_az"] = "字母顺序 (A–Z)",
        ["group_sinus"] = "窦性",
        ["group_arrhythmia"] = "心律失常",
        ["group_conduction"] = "传导障碍",
        ["group_hypertrophy"] = "心肌肥厚",
        ["group_ischemia"] = "缺血",
        ["group_infarction"] = "梗死",
        ["group_electrolyte"] = "电解质紊乱与中毒效应",
        ["group_syndromes"] = "综合征、离子通道病及特殊状态",
        ["group_pacemaker"] = "人工起搏器",
        ["group_special"] = "特殊患者群体与鉴别诊断",
        ["group_pediatric"] = "小儿心电图",
        ["group_newborn"] = "新生儿心电图",
        ["group_pregnant"] = "妊娠期心电图",
        ["group_other"] = "其他",
        ["editor_set_time_title"] = "设置时间 (ms)",
        ["editor_time_unit"] = "ms",
        ["editor_time_format"] = "{0} ms",
        ["editor_set_adc_title"] = "设置 ADC 值",
        ["editor_adc_label"] = "ADC",
        ["editor_adc_format"] = "ADC: {0}",
        ["monitor_speed_title"] = "速度",
        ["monitor_speed_unit"] = "毫米/秒",
        ["monitor_speed_format"] = "{0} 毫米/秒",
        ["monitor_count_format"] = "{0}×",
        ["monitor_columns_one"] = "1 列",
        ["monitor_columns_two"] = "2 列",
        ["monitor_columns_grid"] = "网格",
        ["monitor_columns_one_short"] = "1 列",
        ["monitor_columns_two_short"] = "2 列",
        ["monitor_columns_grid_short"] = "网格",
        ["ecg_open_monitor"] = "在监视器上打开",
        ["monitor_electrodes"] = "电极",
        ["monitor_emd_ebpa"] = "无脉电活动",
        ["monitor_muscle"] = "肌肉",
        ["monitor_eos"] = "心电轴",
        ["monitor_hr_format"] = "心率 {0}",
        ["monitor_tips"] = "提示",
        ["settings_tcp_ip_error"] = "IP 地址格式无效",
        ["settings_tcp_port_error"] = "端口必须在 0–65535 之间",
        ["ecg_point_p_start"] = "P 开始",
        ["ecg_point_p_peak"] = "P 峰值",
        ["ecg_point_p_end"] = "P 结束",
        ["ecg_point_q_peak"] = "Q 峰值",
        ["ecg_point_r_peak"] = "R 峰值",
        ["ecg_point_s_peak"] = "S 峰值",
        ["ecg_point_qrs_start"] = "QRS 开始",
        ["ecg_point_qrs_end"] = "QRS 结束",
        ["ecg_point_t_start"] = "T 开始",
        ["ecg_point_t_peak"] = "T 峰值",
        ["ecg_point_t_end"] = "T 结束",
        ["ecg_interval_p"] = "P",
        ["ecg_interval_qrs"] = "QRS",
        ["ecg_interval_t"] = "T",
        ["ecg_interval_pr"] = "PR",
        ["ecg_interval_st"] = "ST",
        ["ecg_interval_qt"] = "QT",
        ["ecg_interval_rr"] = "R-R",
        ["ecg_rr_value_format"] = "R-R: {0:0.000} 秒",
    };

    private static readonly Dictionary<string, string> Es = new()
    {
        ["data_source_title"] = "Datos ECG",
        ["data_source_description"] = "Selecciona en tu dispositivo un archivo ZIP que contenga los datos ECG.",
        ["data_source_pick_folder"] = "Seleccionar archivo ZIP",
        ["data_source_change_folder"] = "Cambiar archivo ZIP",
        ["data_source_loading"] = "Cargando datos…",
        ["data_source_continue"] = "Continuar",
        ["data_source_retry"] = "Elegir otro ZIP",
        ["data_source_show_details"] = "Ver Detalles",
        ["data_source_close"] = "Cerrar",
        ["data_source_error_bad_manifest"] = "El archivo ZIP contiene un archivo de manifiesto no válido o ausente.",
        ["data_source_error_unreadable"] = "El archivo ZIP seleccionado ya no está accesible.",
        ["data_source_error_empty"] = "No se encontraron archivos ECG en el archivo ZIP seleccionado.",
        ["data_source_export_zip"] = "Exportar ZIP",
        ["course_data_title"] = "Datos del curso",
        ["course_change_zip"] = "Cambiar ZIP de cursos",
        ["course_export_zip"] = "Exportar ZIP de cursos",
        ["data_source_loaded_format"] = "Patologías cargadas: {0}",
        ["data_source_pathologies_title"] = "Patologías Cargadas ({0})",
        ["rhythm_search_placeholder"] = "Ritmo…",
        ["rhythm_course_filter_all"] = "Todos los ritmos",
        ["lecture_selector_title"] = "Lección",
        ["settings_title"] = "Ajustes",
        ["settings_close"] = "CERRAR",
        ["settings_color_scheme"] = "Tema de la aplicación",
        ["theme_light"] = "Claro",
        ["theme_dark"] = "Oscuro",
        ["settings_grid_scheme"] = "Esquema de cuadrícula",
        ["settings_language"] = "Idioma",
        ["settings_tcp_title"] = "Conexión TCP",
        ["settings_tcp_ip"] = "Dirección IP",
        ["settings_tcp_port"] = "Puerto",
        ["tcp_connect"] = "Conectar",
        ["tcp_disconnect"] = "Desconectar",
        ["tcp_status_connected"] = "Conectado",
        ["tcp_status_waiting"] = "Esperando…",
        ["tcp_status_disconnected"] = "Desconectado",
        ["tcp_status_error"] = "Error",
        ["mode_teaching"] = "Enseñanza",
        ["mode_testing"] = "Prueba",
        ["mode_test_constructor"] = "Constructor de Pruebas",
        ["test_select_title"] = "Prueba",
        ["test_start"] = "Iniciar prueba",
        ["test_empty"] = "Aún no hay pruebas. Cree una en el Constructor de Pruebas.",
        ["test_counter_format"] = "{0} de {1}",
        ["test_question_title_format"] = "Pregunta {0}",
        ["test_comment_title"] = "Comentario",
        ["test_correct_answer_format"] = "Respuesta correcta: {0}",
        ["test_next"] = "Siguiente pregunta",
        ["test_finish"] = "Finalizar",
        ["test_time_up"] = "Tiempo agotado",
        ["test_result_title"] = "Prueba completada",
        ["test_result_score_format"] = "Resultado: {0} de {1}",
        ["test_restart"] = "Reiniciar",
        ["test_ctor_intro"] = "Seleccione una prueba para editar o cree una nueva.",
        ["test_ctor_new"] = "Nueva prueba",
        ["test_ctor_new_title"] = "Nueva prueba",
        ["test_ctor_title_label"] = "Título de la prueba",
        ["test_ctor_time_label"] = "Segundos por pregunta (0 = sin tiempo)",
        ["test_ctor_delete"] = "Eliminar",
        ["test_ctor_delete_confirm"] = "¿Eliminar esta prueba?",
        ["test_ctor_save"] = "Guardar",
        ["test_ctor_saved"] = "Guardado",
        ["test_ctor_add_question"] = "Añadir pregunta",
        ["test_ctor_remove_question"] = "Eliminar pregunta",
        ["test_ctor_question_label_format"] = "Pregunta {0}",
        ["test_ctor_question_text"] = "Texto de la pregunta",
        ["test_ctor_option_format"] = "Opción {0}",
        ["test_ctor_correct"] = "Correcta",
        ["test_ctor_comment"] = "Comentario (se muestra al responder)",
        ["test_ctor_ecg"] = "ECG en el monitor",
        ["test_ctor_ecg_none"] = "— ninguno —",
        ["test_ctor_tests_label"] = "Pruebas",
        ["exam_tab_exam"] = "Examen",
        ["exam_tab_results"] = "Resultados",
        ["exam_start"] = "Iniciar examen",
        ["exam_start_title"] = "Iniciar examen",
        ["exam_intro"] = "Introduzca sus datos y elija una prueba para comenzar el examen.",
        ["exam_field_full_name"] = "Nombre completo",
        ["exam_field_group"] = "Grupo",
        ["exam_field_test"] = "Prueba",
        ["exam_no_tests"] = "No hay pruebas disponibles. Cree una en el Constructor de Pruebas.",
        ["exam_finish"] = "Finalizar",
        ["exam_finish_confirm_title"] = "¿Finalizar examen?",
        ["exam_finish_confirm"] = "¿Enviar sus respuestas para calificación? No se puede deshacer.",
        ["exam_passed"] = "Aprobado",
        ["exam_failed"] = "Reprobado",
        ["exam_score_format"] = "{0} de {1}",
        ["exam_new_attempt"] = "Nuevo intento",
        ["exam_unanswered"] = "Sin responder",
        ["exam_results_empty"] = "Aún no hay resultados guardados.",
        ["mode_examination"] = "Examen",
        ["mode_oske"] = "ECOE",
        ["mode_editor"] = "Constructor ECG",
        ["mode_course_constructor"] = "Constructor de Cursos",
        ["compare_button"] = "Comparar",
        ["compare_mode_title"] = "Modo comparación",
        ["compare_placeholder"] = "Toca para añadir comparación",
        ["compare_lead_label"] = "Derivación",
        ["compare_exit"] = "Salir de comparación",
        ["compare_start_new"] = "Nueva comparación",
        ["compare_apply_preset"] = "Aplicar preajuste",
        ["compare_target_title"] = "Seleccionar comparación",
        ["compare_presets"] = "Preajustes guardados",
        ["compare_save_preset_label"] = "Guardar diseño como preajuste:",
        ["compare_save_preset_placeholder"] = "Nombre del preajuste…",
        ["common_ok"] = "Aceptar",
        ["common_cancel"] = "Cancelar",
        ["common_save"] = "Guardar",
        ["settings_blank_sheet"] = "Hoja en blanco",
        ["calc_derived_leads"] = "Calcular derivaciones",
        ["grid_scheme_pink"] = "Rosa",
        ["grid_scheme_blue_gray"] = "Azul/Gris",
        ["grid_scheme_blank"] = "En blanco",
        ["editor_significant_points"] = "Puntos significativos",
        ["editor_sample_label"] = "Muestra: {0}",
        ["editor_p_wave"] = "Onda P",
        ["editor_qrs_complex"] = "Complejo QRS",
        ["editor_t_wave"] = "Onda T",
        ["editor_select_point_hint"] = "Seleccione un punto en el gráfico para marcarlo",
        ["editor_rhythms_title"] = "Ritmos",
        ["fix_drawer"] = "Fijar panel",
        ["welcome_title"] = "Bienvenido al mundo del ECG",
        ["welcome_body"] = "Este simulador responderá a todas tus preguntas sobre el ECG. Estudia ritmos y patologías en un monitor realista, realiza cursos y lecciones interactivas, ponte a prueba y crea tus propios ECG y materiales didácticos.",
        ["welcome_feature_1"] = "Monitor de ECG realista de 12 derivaciones",
        ["welcome_feature_2"] = "Cursos y lecciones con ejemplos interactivos",
        ["welcome_feature_3"] = "Pruebas, exámenes y la estación ECOE para autoevaluación",
        ["welcome_feature_4"] = "Constructores de tus propios ECG, cursos y pruebas",
        ["welcome_tagline"] = "¡Vamos a empezar!",
        ["welcome_start"] = "Empezar",
        ["rhythm_sort_by_group"] = "Por grupos",
        ["rhythm_sort_az"] = "Alfabético (A–Z)",
        ["group_sinus"] = "Sinusal",
        ["group_arrhythmia"] = "Trastornos del ritmo",
        ["group_conduction"] = "Trastornos de la conducción",
        ["group_hypertrophy"] = "Hipertrofia miocárdica",
        ["group_ischemia"] = "Isquemia",
        ["group_infarction"] = "Infarto",
        ["group_electrolyte"] = "Trastornos electrolíticos y efectos tóxicos",
        ["group_syndromes"] = "Síndromes, canalopatías y estados específicos",
        ["group_pacemaker"] = "Marcapasos artificiales",
        ["group_special"] = "Grupos especiales de pacientes y diagnóstico diferencial",
        ["group_pediatric"] = "ECG pediátrico",
        ["group_newborn"] = "ECG neonatal",
        ["group_pregnant"] = "ECG en el embarazo",
        ["group_other"] = "Otros",
        ["editor_set_time_title"] = "Establecer tiempo (ms)",
        ["editor_time_unit"] = "ms",
        ["editor_time_format"] = "{0} ms",
        ["editor_set_adc_title"] = "Establecer valor ADC",
        ["editor_adc_label"] = "ADC",
        ["editor_adc_format"] = "ADC: {0}",
        ["monitor_speed_title"] = "Velocidad",
        ["monitor_speed_unit"] = "mm/s",
        ["monitor_speed_format"] = "{0} mm/s",
        ["monitor_count_format"] = "{0}×",
        ["monitor_columns_one"] = "1 columna",
        ["monitor_columns_two"] = "2 columnas",
        ["monitor_columns_grid"] = "Cuadrícula",
        ["monitor_columns_one_short"] = "1 col.",
        ["monitor_columns_two_short"] = "2 col.",
        ["monitor_columns_grid_short"] = "Cuadr.",
        ["ecg_open_monitor"] = "Abrir en el monitor",
        ["monitor_electrodes"] = "Electrodos",
        ["monitor_emd_ebpa"] = "AESP/AEPS",
        ["monitor_muscle"] = "Músculo",
        ["monitor_eos"] = "EE",
        ["monitor_hr_format"] = "FC {0}",
        ["monitor_tips"] = "Consejos",
        ["settings_tcp_ip_error"] = "Formato de dirección IP no válido",
        ["settings_tcp_port_error"] = "El puerto debe estar entre 0–65535",
        ["ecg_point_p_start"] = "Inicio P",
        ["ecg_point_p_peak"] = "Pico P",
        ["ecg_point_p_end"] = "Fin P",
        ["ecg_point_q_peak"] = "Pico Q",
        ["ecg_point_r_peak"] = "Pico R",
        ["ecg_point_s_peak"] = "Pico S",
        ["ecg_point_qrs_start"] = "Inicio QRS",
        ["ecg_point_qrs_end"] = "Fin QRS",
        ["ecg_point_t_start"] = "Inicio T",
        ["ecg_point_t_peak"] = "Pico T",
        ["ecg_point_t_end"] = "Fin T",
        ["ecg_interval_p"] = "P",
        ["ecg_interval_qrs"] = "QRS",
        ["ecg_interval_t"] = "T",
        ["ecg_interval_pr"] = "PR",
        ["ecg_interval_st"] = "ST",
        ["ecg_interval_qt"] = "QT",
        ["ecg_interval_rr"] = "R-R",
        ["ecg_rr_value_format"] = "R-R: {0:0.000} s",
    };
}
